---
# permissions to approve all cert-manager.k8s.oci.com requests
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-controller-approve:cert-manager-k8s-oci-com
rules:
  - apiGroups:
      - cert-manager.io
    resources:
      - signers
    verbs:
      - approve
    resourceNames:
      - ocica.cert-manager.k8s.oci.com/*
