---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ocica.cert-manager.io
  resources:
  - ocicaclusterissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocica.cert-manager.io
  resources:
  - ocicaclusterissuers/finalizers
  verbs:
  - update
- apiGroups:
  - ocica.cert-manager.io
  resources:
  - ocicaclusterissuers/status
  verbs:
  - get
  - patch
  - update
