name: test
on:
  - pull_request

env:
  REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
  IMAGE_REGISTRY: docker.io
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19' ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: run tests
        run: make test
      - name: build container
        uses: redhat-actions/buildah-build@v2
        with:
          platforms: linux/amd64 linux/arm64v8
          image: docker.io/jimbotux/oci-private-issuer
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile
